2024-08-22 09:03:12,086 INFO: Microblog startup [in /home/lasssek/Documents/flaskTest/flaskTest/app/__init__.py:42]
2024-08-22 09:03:34,250 ERROR: Exception on /index [GET] [in /home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/app/routes.py", line 25, in index
    posts = db.paginate (current_user.following_posts (), page=page, per_page=app.config['POSTS_PER_PAGE'], error_out=False);
                                                                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2024-08-22 09:03:37,444 ERROR: Exception on /user/Daniel [GET] [in /home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/app/routes.py", line 82, in user
    per_page=app.config['POSTS_PER_PAGE'],
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2024-08-22 09:03:39,502 ERROR: Exception on /user/Daniel [GET] [in /home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/app/routes.py", line 82, in user
    per_page=app.config['POSTS_PER_PAGE'],
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2024-08-22 09:03:40,904 ERROR: Exception on /index [GET] [in /home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/app/routes.py", line 25, in index
    posts = db.paginate (current_user.following_posts (), page=page, per_page=app.config['POSTS_PER_PAGE'], error_out=False);
                                                                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2024-08-22 09:03:41,986 ERROR: Exception on /explore [GET] [in /home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/app/routes.py", line 160, in explore
    posts = db.paginate (query, page=page, per_page=app.config['POSTS_PER_PAGE'], error_out=False)
                                                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2024-08-22 09:03:42,775 ERROR: Exception on /explore [GET] [in /home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lasssek/Documents/flaskTest/flaskTest/app/routes.py", line 160, in explore
    posts = db.paginate (query, page=page, per_page=app.config['POSTS_PER_PAGE'], error_out=False)
                                                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
